package com.jack.lottery.mapper;

import com.jack.lottery.entity.CardInfo;
import com.jack.lottery.entity.CardInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated
     */
    int countByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated
     */
    int deleteByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated
     */
    int insert(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated
     */
    int insertSelective(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated
     */
    List<CardInfo> selectByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated
     */
    CardInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CardInfo record, @Param("example") CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CardInfo record, @Param("example") CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CardInfo record);
}