package com.jack.lottery.mapper;

import com.jack.lottery.entity.LotteryTerm;
import com.jack.lottery.entity.LotteryTermExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LotteryTermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_term
     *
     * @mbggenerated
     */
    int countByExample(LotteryTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_term
     *
     * @mbggenerated
     */
    int deleteByExample(LotteryTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_term
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_term
     *
     * @mbggenerated
     */
    int insert(LotteryTerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_term
     *
     * @mbggenerated
     */
    int insertSelective(LotteryTerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_term
     *
     * @mbggenerated
     */
    List<LotteryTerm> selectByExample(LotteryTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_term
     *
     * @mbggenerated
     */
    LotteryTerm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_term
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LotteryTerm record, @Param("example") LotteryTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_term
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LotteryTerm record, @Param("example") LotteryTermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_term
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LotteryTerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_term
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LotteryTerm record);
}