package com.jack.lottery.mapper;

import com.jack.lottery.entity.RechargeOrder;
import com.jack.lottery.entity.RechargeOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RechargeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int countByExample(RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int deleteByExample(RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int insert(RechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int insertSelective(RechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    List<RechargeOrder> selectByExample(RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    RechargeOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RechargeOrder record, @Param("example") RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RechargeOrder record, @Param("example") RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RechargeOrder record);
}