package com.jack.lottery.mapper;

import com.jack.lottery.entity.SMSCode;
import com.jack.lottery.entity.SMSCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SMSCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int countByExample(SMSCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int deleteByExample(SMSCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int insert(SMSCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int insertSelective(SMSCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    List<SMSCode> selectByExample(SMSCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    SMSCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SMSCode record, @Param("example") SMSCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SMSCode record, @Param("example") SMSCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SMSCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SMSCode record);
}