package com.jack.lottery.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LotteryOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    public LotteryOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Long value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Long value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Long value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Long value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Long value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Long> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Long> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Long value1, Long value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Long value1, Long value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(BigDecimal value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(BigDecimal value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(BigDecimal value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(BigDecimal value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<BigDecimal> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<BigDecimal> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtIsNull() {
            addCriterion("order_id_ext is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtIsNotNull() {
            addCriterion("order_id_ext is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtEqualTo(String value) {
            addCriterion("order_id_ext =", value, "orderIdExt");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtNotEqualTo(String value) {
            addCriterion("order_id_ext <>", value, "orderIdExt");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtGreaterThan(String value) {
            addCriterion("order_id_ext >", value, "orderIdExt");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtGreaterThanOrEqualTo(String value) {
            addCriterion("order_id_ext >=", value, "orderIdExt");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtLessThan(String value) {
            addCriterion("order_id_ext <", value, "orderIdExt");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtLessThanOrEqualTo(String value) {
            addCriterion("order_id_ext <=", value, "orderIdExt");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtLike(String value) {
            addCriterion("order_id_ext like", value, "orderIdExt");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtNotLike(String value) {
            addCriterion("order_id_ext not like", value, "orderIdExt");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtIn(List<String> values) {
            addCriterion("order_id_ext in", values, "orderIdExt");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtNotIn(List<String> values) {
            addCriterion("order_id_ext not in", values, "orderIdExt");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtBetween(String value1, String value2) {
            addCriterion("order_id_ext between", value1, value2, "orderIdExt");
            return (Criteria) this;
        }

        public Criteria andOrderIdExtNotBetween(String value1, String value2) {
            addCriterion("order_id_ext not between", value1, value2, "orderIdExt");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(Integer value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(Integer value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(Integer value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(Integer value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(Integer value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<Integer> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<Integer> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(Integer value1, Integer value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(Integer value1, Integer value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andMutiplyIsNull() {
            addCriterion("mutiply is null");
            return (Criteria) this;
        }

        public Criteria andMutiplyIsNotNull() {
            addCriterion("mutiply is not null");
            return (Criteria) this;
        }

        public Criteria andMutiplyEqualTo(Integer value) {
            addCriterion("mutiply =", value, "mutiply");
            return (Criteria) this;
        }

        public Criteria andMutiplyNotEqualTo(Integer value) {
            addCriterion("mutiply <>", value, "mutiply");
            return (Criteria) this;
        }

        public Criteria andMutiplyGreaterThan(Integer value) {
            addCriterion("mutiply >", value, "mutiply");
            return (Criteria) this;
        }

        public Criteria andMutiplyGreaterThanOrEqualTo(Integer value) {
            addCriterion("mutiply >=", value, "mutiply");
            return (Criteria) this;
        }

        public Criteria andMutiplyLessThan(Integer value) {
            addCriterion("mutiply <", value, "mutiply");
            return (Criteria) this;
        }

        public Criteria andMutiplyLessThanOrEqualTo(Integer value) {
            addCriterion("mutiply <=", value, "mutiply");
            return (Criteria) this;
        }

        public Criteria andMutiplyIn(List<Integer> values) {
            addCriterion("mutiply in", values, "mutiply");
            return (Criteria) this;
        }

        public Criteria andMutiplyNotIn(List<Integer> values) {
            addCriterion("mutiply not in", values, "mutiply");
            return (Criteria) this;
        }

        public Criteria andMutiplyBetween(Integer value1, Integer value2) {
            addCriterion("mutiply between", value1, value2, "mutiply");
            return (Criteria) this;
        }

        public Criteria andMutiplyNotBetween(Integer value1, Integer value2) {
            addCriterion("mutiply not between", value1, value2, "mutiply");
            return (Criteria) this;
        }

        public Criteria andAdditionIsNull() {
            addCriterion("addition is null");
            return (Criteria) this;
        }

        public Criteria andAdditionIsNotNull() {
            addCriterion("addition is not null");
            return (Criteria) this;
        }

        public Criteria andAdditionEqualTo(Integer value) {
            addCriterion("addition =", value, "addition");
            return (Criteria) this;
        }

        public Criteria andAdditionNotEqualTo(Integer value) {
            addCriterion("addition <>", value, "addition");
            return (Criteria) this;
        }

        public Criteria andAdditionGreaterThan(Integer value) {
            addCriterion("addition >", value, "addition");
            return (Criteria) this;
        }

        public Criteria andAdditionGreaterThanOrEqualTo(Integer value) {
            addCriterion("addition >=", value, "addition");
            return (Criteria) this;
        }

        public Criteria andAdditionLessThan(Integer value) {
            addCriterion("addition <", value, "addition");
            return (Criteria) this;
        }

        public Criteria andAdditionLessThanOrEqualTo(Integer value) {
            addCriterion("addition <=", value, "addition");
            return (Criteria) this;
        }

        public Criteria andAdditionIn(List<Integer> values) {
            addCriterion("addition in", values, "addition");
            return (Criteria) this;
        }

        public Criteria andAdditionNotIn(List<Integer> values) {
            addCriterion("addition not in", values, "addition");
            return (Criteria) this;
        }

        public Criteria andAdditionBetween(Integer value1, Integer value2) {
            addCriterion("addition between", value1, value2, "addition");
            return (Criteria) this;
        }

        public Criteria andAdditionNotBetween(Integer value1, Integer value2) {
            addCriterion("addition not between", value1, value2, "addition");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinIsNull() {
            addCriterion("stop_after_win is null");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinIsNotNull() {
            addCriterion("stop_after_win is not null");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinEqualTo(String value) {
            addCriterion("stop_after_win =", value, "stopAfterWin");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinNotEqualTo(String value) {
            addCriterion("stop_after_win <>", value, "stopAfterWin");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinGreaterThan(String value) {
            addCriterion("stop_after_win >", value, "stopAfterWin");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinGreaterThanOrEqualTo(String value) {
            addCriterion("stop_after_win >=", value, "stopAfterWin");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinLessThan(String value) {
            addCriterion("stop_after_win <", value, "stopAfterWin");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinLessThanOrEqualTo(String value) {
            addCriterion("stop_after_win <=", value, "stopAfterWin");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinLike(String value) {
            addCriterion("stop_after_win like", value, "stopAfterWin");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinNotLike(String value) {
            addCriterion("stop_after_win not like", value, "stopAfterWin");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinIn(List<String> values) {
            addCriterion("stop_after_win in", values, "stopAfterWin");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinNotIn(List<String> values) {
            addCriterion("stop_after_win not in", values, "stopAfterWin");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinBetween(String value1, String value2) {
            addCriterion("stop_after_win between", value1, value2, "stopAfterWin");
            return (Criteria) this;
        }

        public Criteria andStopAfterWinNotBetween(String value1, String value2) {
            addCriterion("stop_after_win not between", value1, value2, "stopAfterWin");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeIsNull() {
            addCriterion("lottery_type is null");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeIsNotNull() {
            addCriterion("lottery_type is not null");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeEqualTo(String value) {
            addCriterion("lottery_type =", value, "lotteryType");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeNotEqualTo(String value) {
            addCriterion("lottery_type <>", value, "lotteryType");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeGreaterThan(String value) {
            addCriterion("lottery_type >", value, "lotteryType");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeGreaterThanOrEqualTo(String value) {
            addCriterion("lottery_type >=", value, "lotteryType");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeLessThan(String value) {
            addCriterion("lottery_type <", value, "lotteryType");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeLessThanOrEqualTo(String value) {
            addCriterion("lottery_type <=", value, "lotteryType");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeLike(String value) {
            addCriterion("lottery_type like", value, "lotteryType");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeNotLike(String value) {
            addCriterion("lottery_type not like", value, "lotteryType");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeIn(List<String> values) {
            addCriterion("lottery_type in", values, "lotteryType");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeNotIn(List<String> values) {
            addCriterion("lottery_type not in", values, "lotteryType");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeBetween(String value1, String value2) {
            addCriterion("lottery_type between", value1, value2, "lotteryType");
            return (Criteria) this;
        }

        public Criteria andLotteryTypeNotBetween(String value1, String value2) {
            addCriterion("lottery_type not between", value1, value2, "lotteryType");
            return (Criteria) this;
        }

        public Criteria andLotteryTermIsNull() {
            addCriterion("lottery_term is null");
            return (Criteria) this;
        }

        public Criteria andLotteryTermIsNotNull() {
            addCriterion("lottery_term is not null");
            return (Criteria) this;
        }

        public Criteria andLotteryTermEqualTo(String value) {
            addCriterion("lottery_term =", value, "lotteryTerm");
            return (Criteria) this;
        }

        public Criteria andLotteryTermNotEqualTo(String value) {
            addCriterion("lottery_term <>", value, "lotteryTerm");
            return (Criteria) this;
        }

        public Criteria andLotteryTermGreaterThan(String value) {
            addCriterion("lottery_term >", value, "lotteryTerm");
            return (Criteria) this;
        }

        public Criteria andLotteryTermGreaterThanOrEqualTo(String value) {
            addCriterion("lottery_term >=", value, "lotteryTerm");
            return (Criteria) this;
        }

        public Criteria andLotteryTermLessThan(String value) {
            addCriterion("lottery_term <", value, "lotteryTerm");
            return (Criteria) this;
        }

        public Criteria andLotteryTermLessThanOrEqualTo(String value) {
            addCriterion("lottery_term <=", value, "lotteryTerm");
            return (Criteria) this;
        }

        public Criteria andLotteryTermLike(String value) {
            addCriterion("lottery_term like", value, "lotteryTerm");
            return (Criteria) this;
        }

        public Criteria andLotteryTermNotLike(String value) {
            addCriterion("lottery_term not like", value, "lotteryTerm");
            return (Criteria) this;
        }

        public Criteria andLotteryTermIn(List<String> values) {
            addCriterion("lottery_term in", values, "lotteryTerm");
            return (Criteria) this;
        }

        public Criteria andLotteryTermNotIn(List<String> values) {
            addCriterion("lottery_term not in", values, "lotteryTerm");
            return (Criteria) this;
        }

        public Criteria andLotteryTermBetween(String value1, String value2) {
            addCriterion("lottery_term between", value1, value2, "lotteryTerm");
            return (Criteria) this;
        }

        public Criteria andLotteryTermNotBetween(String value1, String value2) {
            addCriterion("lottery_term not between", value1, value2, "lotteryTerm");
            return (Criteria) this;
        }

        public Criteria andLotteryContentIsNull() {
            addCriterion("lottery_content is null");
            return (Criteria) this;
        }

        public Criteria andLotteryContentIsNotNull() {
            addCriterion("lottery_content is not null");
            return (Criteria) this;
        }

        public Criteria andLotteryContentEqualTo(String value) {
            addCriterion("lottery_content =", value, "lotteryContent");
            return (Criteria) this;
        }

        public Criteria andLotteryContentNotEqualTo(String value) {
            addCriterion("lottery_content <>", value, "lotteryContent");
            return (Criteria) this;
        }

        public Criteria andLotteryContentGreaterThan(String value) {
            addCriterion("lottery_content >", value, "lotteryContent");
            return (Criteria) this;
        }

        public Criteria andLotteryContentGreaterThanOrEqualTo(String value) {
            addCriterion("lottery_content >=", value, "lotteryContent");
            return (Criteria) this;
        }

        public Criteria andLotteryContentLessThan(String value) {
            addCriterion("lottery_content <", value, "lotteryContent");
            return (Criteria) this;
        }

        public Criteria andLotteryContentLessThanOrEqualTo(String value) {
            addCriterion("lottery_content <=", value, "lotteryContent");
            return (Criteria) this;
        }

        public Criteria andLotteryContentLike(String value) {
            addCriterion("lottery_content like", value, "lotteryContent");
            return (Criteria) this;
        }

        public Criteria andLotteryContentNotLike(String value) {
            addCriterion("lottery_content not like", value, "lotteryContent");
            return (Criteria) this;
        }

        public Criteria andLotteryContentIn(List<String> values) {
            addCriterion("lottery_content in", values, "lotteryContent");
            return (Criteria) this;
        }

        public Criteria andLotteryContentNotIn(List<String> values) {
            addCriterion("lottery_content not in", values, "lotteryContent");
            return (Criteria) this;
        }

        public Criteria andLotteryContentBetween(String value1, String value2) {
            addCriterion("lottery_content between", value1, value2, "lotteryContent");
            return (Criteria) this;
        }

        public Criteria andLotteryContentNotBetween(String value1, String value2) {
            addCriterion("lottery_content not between", value1, value2, "lotteryContent");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andMsgIsNull() {
            addCriterion("msg is null");
            return (Criteria) this;
        }

        public Criteria andMsgIsNotNull() {
            addCriterion("msg is not null");
            return (Criteria) this;
        }

        public Criteria andMsgEqualTo(String value) {
            addCriterion("msg =", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotEqualTo(String value) {
            addCriterion("msg <>", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThan(String value) {
            addCriterion("msg >", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThanOrEqualTo(String value) {
            addCriterion("msg >=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThan(String value) {
            addCriterion("msg <", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThanOrEqualTo(String value) {
            addCriterion("msg <=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLike(String value) {
            addCriterion("msg like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotLike(String value) {
            addCriterion("msg not like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgIn(List<String> values) {
            addCriterion("msg in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotIn(List<String> values) {
            addCriterion("msg not in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgBetween(String value1, String value2) {
            addCriterion("msg between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotBetween(String value1, String value2) {
            addCriterion("msg not between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lottery_order
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lottery_order
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}